steps:
  #Run test
<<<<<<< HEAD
  - name:  gradle:7.4.0-jdk17
=======
  - name: gradle:7.3.3-jdk15
>>>>>>> 4e652d1 (Add handlers to make a response to a mention event)
    entrypoint: gradle
  # Build gradle
  - name: gradle:7.4.0-jdk17
    entrypoint: gradle
    args: [ "assemble" ]
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/idea-slackbot:$COMMIT_SHA','--build-arg=JAR_FILE=/build/libs/norberbot.jar','.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/idea-slackbot:$COMMIT_SHA' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'idea-slackbot'
    - '--image'
    - 'gcr.io/$PROJECT_ID/idea-slackbot:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
images:
  - 'gcr.io/$PROJECT_ID/idea-slackbot:$COMMIT_SHA'